[package]
name = "colosseum-core"
version = "0.1.0"
authors = ["Chay Nabors <chaynabors@gmail.com>"]
edition = "2018"

[dependencies]
include_dir = "0.6.0"
lazy_static = "1.4.0"
ncollide3d = "0.26.1"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
