[package]
name = "colosseum"
version = "0.1.0"
authors = ["Chay Nabors <chaynabors@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
variant_count = "1.0.0"
